# https://docs.docker.com/compose/compose-file/
version: '3'
services: # must call it 'services'?
  proxy:
    image: nginx
    build:
      dockerfile: nginx.dockerfile
    volumes:
    - ./conf/nginx/templates:/etc/nginx/templates
    - ./www:/srv/www:ro # nginx needs access to application files in order to serve static files
    ports:
    - "8080:80"
    environment:
    - NGINX_ENVSUBST_TEMPLATE_DIR=/etc/nginx/templates # default
    - NGINX_ENVSUBST_TEMPLATE_SUFFIX=.template         # default
    - NGINX_ENVSUBST_OUTPUT_DIR=/etc/nginx/conf.d      # default
    - NGINX_SERVER_NAME=localhost
    - NGINX_LISTEN=80
    - NGINX_LISTEN_SSL=443
  app:
    image: php
    build:
      dockerfile: php.dockerfile
    volumes:
    - ./www:/srv/www
    working_dir: /srv/www
    expose:
    - "9000"

